name: Gitee repos mirror periodic job

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      if: always()
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ao-space
        dst: gitee/ao-space
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: org
        timeout: 600
        debug: true
        force_update: false
        static_list: "ao.space"

    - name: Debug repo owner
      run: |
        echo ${{ github.repository_owner }}
        echo ${{ github.actor }}